config_form.settings_form:
  path: '/admin/config/xai/settings'
  defaults:
    _form: '\Drupal\xai\Form\SettingsForm'
    _title: 'SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
