<?php
use Drupal\Core\Form\FormStateInterface;

function webform_contact_form_alter(&$form, $form_state, $form_id) {

    //if form is avaliable then continue to the next code 
	if(isset($form['#webform_id']) && $form['#webform_id'] == 'attorneys_contact_us'){
		$current_path = \Drupal::service('path.current')->getPath();
	//fetch the current node if from url that passed in yes button url .	
  	$nid = \Drupal::request()->query->get('aid');
		
	// Aid = Sunique attorneys id form url.
	// if nid has a value then fetch the name form nid .
	  if($nid){
		  //get the node values by node id 
	    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
	    $name = $node->get('title')->getValue();
	    $attorney_name = $name[0]['value']; 

	 	$form['elements']['attorneys_contact_us_label']['#prefix'] = '<div class="row"><div class="col-lg-8 mx-auto sec-title"><h2>';
     	$form['elements']['attorneys_contact_us_label']['#suffix'] = '</h2>';
		
		
		$form['elements']['your_email_will_be_sent_to_']['#prefix'] = '<h4>';
		$form['elements']['your_email_will_be_sent_to_']['#title'] = 'Your email will be sent to: '.$attorney_name;
		$form['elements']['your_email_will_be_sent_to_']['#suffix'] = '</h4></div></div>'; 
	 	   
	  } 
	  else {
	   	$form['#attributes']['class'][] = 'webform-hide-custom';
	  }
	  
	}
}
